### ISSUE TITLE
[Bug?]: https with cookies broken, due to appendHeader

### ISSUE THREAD

**Issue by birkskyum** [solidjs/solid-start#974]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When adding a Set-Cookie header while running solid-start with https the following error occur: 

```sh
An unhandled error occured: TypeError: res.appendHeader is not a function
    at handleNodeResponse (file:///Users/admin/repos/app/node_modules/solid-start/node/fetch.js:168:11)
```

### Expected behavior 🤔

I expected the cookie to just be set.

### Steps to reproduce 🕹

Repro here:

https://github.com/birkskyum/solid-start-https-appendHeader-0.3.1

3 changes are made:

* I added a simple API route called test.ts that returns a response with a Set-Cookie header.
* I also added the https config to the vite.config.ts
* I installed the `vite-plugin-mkcert`

### Context 🔦

I want to keep [using https in development](https://auth0.com/blog/using-https-in-your-development-environment/), because I use Auth0. This worked with solid-start up to 0.2.29.

Related 
- https://github.com/solidjs/solid-start/issues/953#issuecomment-1670492120
- https://github.com/solidjs/solid-start/issues/971

Setting https: false make the code run with http, which is how I narrowed it down so far. ([link](https://github.com/solidjs/solid-start/issues/953#issuecomment-1670492120)).

### Your environment 🌎

```shell
macOS arm64
Node 18 and 20. Node 16 breaks even earlier
```
